-- MySQL Script generated by MySQL Workbench
-- Tue Mar  2 21:24:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema umarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema umarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `umarket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `umarket` ;

-- -----------------------------------------------------
-- Table `umarket`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`administrador` ;

CREATE TABLE IF NOT EXISTS `umarket`.`administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nombreAdministrador` VARCHAR(45) NOT NULL,
  `direccionAdministrador` VARCHAR(45) NOT NULL,
  `telefonoAdministrador` VARCHAR(15) NOT NULL,
  `correoAdministrador` VARCHAR(35) NOT NULL,
  `urlFoto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad Administrador y sus atributos.';


-- -----------------------------------------------------
-- Table `umarket`.`distribuidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`distribuidor` ;

CREATE TABLE IF NOT EXISTS `umarket`.`distribuidor` (
  `idDistribuidor` INT NOT NULL AUTO_INCREMENT,
  `nombreDistribuidor` VARCHAR(45) NOT NULL,
  `correoDistribuidor` VARCHAR(45) NOT NULL,
  `telefonoDistribuidor` VARCHAR(15) NOT NULL,
  `domicilioDistribuidor` VARCHAR(45) NOT NULL,
  `ramo` INT NOT NULL,
  `identificacionDistribuidor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistribuidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad Distribuidor y sus atributos.';


-- -----------------------------------------------------
-- Table `umarket`.`usuariocv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`usuariocv` ;

CREATE TABLE IF NOT EXISTS `umarket`.`usuariocv` (
  `idUsuarioCV` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuarioCV` VARCHAR(45) NOT NULL,
  `direccionUsuarioCV` VARCHAR(45) NOT NULL,
  `telefonoUsuarioCV` VARCHAR(15) NOT NULL,
  `correoUsuarioCV` VARCHAR(45) NOT NULL,
  `credencialUsuarioCV` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarioCV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad UsuarioCV y sus atributos.';


-- -----------------------------------------------------
-- Table `umarket`.`mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`mensajes` ;

CREATE TABLE IF NOT EXISTS `umarket`.`mensajes` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `fechaMensaje` DATE NOT NULL,
  `remitente` INT NOT NULL,
  `destinatario` INT NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk1_remitente_idx` (`remitente` ASC) VISIBLE,
  INDEX `fk2_destinatario_idx` (`destinatario` ASC) VISIBLE,
  CONSTRAINT `fk1_remitente`
    FOREIGN KEY (`remitente`)
    REFERENCES `umarket`.`usuariocv` (`idUsuarioCV`),
  CONSTRAINT `fk2_destinatario`
    FOREIGN KEY (`destinatario`)
    REFERENCES `umarket`.`distribuidor` (`idDistribuidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad Mensajes y sus atributos.';


-- -----------------------------------------------------
-- Table `umarket`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `umarket`.`publicaciones` (
  `idPublicaciones` INT NOT NULL AUTO_INCREMENT,
  `fechaPublicacion` VARCHAR(45) NOT NULL,
  `creadorUPublicacion` INT NULL DEFAULT NULL,
  `creadorDPublicacion` INT NULL DEFAULT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`idPublicaciones`),
  INDEX `fk1_creadorUsuario_idx` (`creadorUPublicacion` ASC) VISIBLE,
  INDEX `fk2_creadorDistribuidor_idx` (`creadorDPublicacion` ASC) VISIBLE,
  CONSTRAINT `fk1_creadorUsuario`
    FOREIGN KEY (`creadorUPublicacion`)
    REFERENCES `umarket`.`usuariocv` (`idUsuarioCV`),
  CONSTRAINT `fk2_creadorDistribuidor`
    FOREIGN KEY (`creadorDPublicacion`)
    REFERENCES `umarket`.`distribuidor` (`idDistribuidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad Publicaciones y sus atributos.';


-- -----------------------------------------------------
-- Table `umarket`.`soporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umarket`.`soporte` ;

CREATE TABLE IF NOT EXISTS `umarket`.`soporte` (
  `idSoporte` INT NOT NULL AUTO_INCREMENT,
  `nombreSoporte` VARCHAR(45) NOT NULL,
  `direccionSoporte` VARCHAR(45) NOT NULL,
  `telefonoSoporte` VARCHAR(15) NOT NULL,
  `correoSoporte` VARCHAR(45) NOT NULL,
  `fotoSoporte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSoporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se describe la entidad Soporte y sus atributos.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
